server:
  port: 8282

spring:
  application:
    name: zuul
  cloud:
    config:
      uri: http://localhost:8080
  output:
    ansi:
      enabled: always

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8181/eureka}